### ISSUE TITLE
Second compilation of mv_driver fails

### ISSUE THREAD

**Issue by furgalep** [ethz-asl/matrixvision_camera#1]
Trying to compile the mv_driver package succeeds the first time, then fails as wget refuses to redownload and exits with an error:

```
ptf@V-Charge-ubuntu:~/Work/ethz/code/ros_vc/matrixvision_camera/mv_driver$ make
./make.sh
### downloading and unpacking drivers to /home/ptf/Work/ethz/code/ros_vc/matrixvision_camera/mv_driver ###
File `mvGenTL_Acquire-x86_64_ABI2-2.5.1.tgz' already there; not retrieving.
make: *** [all] Error 1
```

Scanning the wget man page, I didn't see a flag that would help here (although there probably is one).

**Comment by simonlynen** [comment]
use wget -N which overwrites if time of size different. This should help 
here.

Simon

**Comment by furgalep** [comment]
Hrm...It seems that the problem is the -nc flag

-N conflicts with -nc

If I remove -nc and add -N, wget complains:

```
WARNING: timestamping does nothing in combination with -O. See the manual
for details.
```

These are the offending lines.

```
wget -nc -O $BLUECOUGAR_TARNAME.tgz  $BLUECOUGAR_URL/$BLUECOUGAR_TARNAME.tgz
wget -nc -O $BLUEFOX_TARNAME.tgz  $BLUEFOX_URL/$BLUEFOX_TARNAME.tgz
```

**Comment by simonlynen** [comment]
OK, can we clean these archives before a build and only on successful 
install touch a respective file?

Thanks for fixing the links
