### ISSUE TITLE
make use ros_timestamps on as default

### ISSUE THREAD

**Issue by simonlynen** [ethz-asl/matrixvision_camera#2]

**Comment by furgalep** [comment]
Do we know how the other timestamps work?

**Comment by simonlynen** [comment]
markus said they are rather random, which makes them perfect

**Comment by furgalep** [comment]
Mathias will look in to the other timestamps. We need them to synchronize our camera system. For now, you are probably right, though.

**Comment by simonlynen** [comment]
// get the image timestamp:
    double current_image_time = timeUs2Double(req->infoTimeStamp_us.read()) \* 1.0e-6;
    image.header.stamp = ros::Time(current_image_time);

**Comment by furgalep** [comment]
hmmm....

**Comment by simonlynen** [comment]
Matrix vision, impact

```
/// \brief An integer property \b (read-only) containing a timestamp (in us) defining the time the device started the exposure of the image associated with this \b mvIMPACT::acquire::Request object.
```

**Comment by furgalep** [comment]
I had some trouble getting properties from the request object. If you scroll down a bit in our code, you will see that I was trying to grab information from it and stick it in the image. Things didn't go well...values were not filled in as I expected.

**Comment by simonlynen** [comment]
depending on the room temperature you can make time go by really fast...

**Comment by furgalep** [comment]
In any case, that timestamp isn't time since the 1970s so making it a ros::Time is probably bad.

**Comment by markusachtelik** [comment]
I also found some weirdness a while ago with the MV time stamps. So lets for now use ros::Time::now() by default at image arrival to have at least working ish time stamps

Am 09.04.2013 um 21:24 schrieb "Paul Furgale" <notifications@github.com<mailto:notifications@github.com>>:

In any case, that timestamp isn't time since the 1970s so making it a ros::Time is probably bad.
